version: '3'

services:
    app:
        working_dir: ${PROJECT_CONTAINER_PATH}
        volumes:
            - ../.:${PROJECT_CONTAINER_PATH}
    nginx:
        volumes:
            - ../.:${PROJECT_CONTAINER_PATH}
            - ../app/server/nginx/app.conf:/etc/nginx/conf.d/app.conf
