version: '3'

services:
    app:
        working_dir: ${PROJECT_CONTAINER_PATH}
        volumes:
            - ../.:${PROJECT_CONTAINER_PATH}
            - ./php/100-app.ini:/usr/local/etc/php/conf.d/100-app.ini
    nginx:
        volumes:
            - ../.:${PROJECT_CONTAINER_PATH}
            - ../app/server/nginx/app.conf:/etc/nginx/conf.d/app.conf
